---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
        
    - name: Installs nginx web server
      yum : name=nginx state=present
      become: yes
      become_method: sudo
      notify:
        - start nginx
   

  handlers:
    - name: start nginx
      become: yes
      become_method: sudo
      service: name=nginx state=restarted
